const mongoose = require('mongoose');
const { TIMEZONE_VALUES } = require('../utils/timezone');
const { PRICING_MODELS, CURRENCIES, BILLING_PERIODS } = require('../utils/adPricingLogic');

// A Campaign belongs to one Advertiser and groups one or more
// Advertisements under a shared budget, pricing model and date range.
//
// STATUS LIFECYCLE
// -----------------
// draft / pending_review / rejected / cancelled / completed are set only
// by an admin action (never touched automatically).
//
// approved / scheduled / active / paused / expired are the "managed"
// statuses — once a campaign is in one of these, campaignController's
// schedule engine keeps it in sync with the clock every time campaigns
// are read: it becomes "scheduled" before startDate, "active" once the
// window opens, and "expired" once endDate passes. "paused" is a
// deliberate admin override that blocks the auto-activate step (but still
// expires on schedule, so a forgotten paused campaign doesn't linger
// forever). See campaignController.js `computeManagedStatus`.
const STATUSES = [
  'draft',
  'pending_review',
  'approved',
  'scheduled',
  'active',
  'paused',
  'completed',
  'expired',
  'cancelled',
  'rejected'
];

const MANAGED_STATUSES = ['approved', 'scheduled', 'active', 'paused', 'expired'];

const campaignSchema = new mongoose.Schema({
  name: { type: String, required: true, trim: true },

  // Human-readable identifier shown in the console (e.g. "CMP-0001").
  // Generated by the controller layer when it's built — the schema just
  // enforces uniqueness here.
  campaignCode: { type: String, required: true, unique: true },

  advertiser: { type: mongoose.Schema.Types.ObjectId, ref: 'Advertiser', required: true, index: true },
  description: { type: String, default: '' },

  budget: {
    total: { type: Number, default: 0 },
    currency: { type: String, default: 'USD' }
  },

  // LEGACY (pre-Part-10B): a simple, informal pricing hint. Left
  // untouched for backward compatibility with existing campaigns/UI, but
  // NOT read by revenue calculation — see `pricing` below, which is the
  // one authoritative pricing config as of Part 10B.
  // flat = one fixed price for the whole campaign regardless of delivery
  pricingModel: { type: String, enum: ['CPM', 'CPC', 'CPD', 'flat'], default: 'flat' },
  pricingRate: { type: Number, default: 0 }, // rate per 1000 impr. / per click / per day, or flat total

  // PART 10B: Advertising Pricing & Revenue Management. Absent/partial
  // until an admin explicitly configures it — a campaign with no
  // `pricing.model` is simply "Pricing not configured" (never a
  // fabricated revenue number). See utils/adPricingLogic.js for the
  // shared vocabulary and validation, and services/adRevenueService.js
  // for how this feeds Estimated Revenue.
  pricing: {
    model: { type: String, enum: PRICING_MODELS, default: null },
    rate: { type: Number, default: null },
    currency: { type: String, enum: CURRENCIES, default: null },
    billingPeriod: { type: String, enum: BILLING_PERIODS, default: null },
    includedImpressions: { type: Number, default: 0 },
    includedClicks: { type: Number, default: 0 },
    notes: { type: String, default: '' },
    configuredBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User', default: null },
    configuredAt: { type: Date, default: null }
  },

  targetImpressions: { type: Number, default: 0 },
  targetClicks: { type: Number, default: 0 },

  // Both stored as absolute UTC instants — the wall-clock date/time the
  // admin entered is combined with `timezone` at write time (see
  // utils/timezone.js) so schedule comparisons are always a simple UTC-vs-UTC
  // check, regardless of which zone the campaign was authored in.
  startDate: { type: Date, required: true },
  endDate: { type: Date, required: true },
  timezone: { type: String, enum: TIMEZONE_VALUES, default: 'Asia/Kolkata' },

  status: { type: String, enum: STATUSES, default: 'draft' },

  internalNotes: { type: String, default: '' }
}, { timestamps: true });

campaignSchema.index({ status: 1 });
campaignSchema.index({ startDate: 1 });
campaignSchema.index({ endDate: 1 });
campaignSchema.index({ advertiser: 1, status: 1 });

campaignSchema.statics.STATUSES = STATUSES;
campaignSchema.statics.MANAGED_STATUSES = MANAGED_STATUSES;

module.exports = mongoose.model('Campaign', campaignSchema);
